---
title: "Bayesian_Stats"
author: "Erin Anderson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(coda)
library(rjags)
```

```{r 1, include=TRUE}
set.seed(812) # set seed, i'm a leo it's my birthday <3; feel free to change it up <3
titi_ppt <- rpois(n = 7, lambda = 13.8) # "collect" data via playback point transect
titi_homerange <- rpois(n = 7, lambda = 16) # "collect" data via homerange
```

```{r 2, include=TRUE}
# are these consistent with 15 groups?
t.test(titi_homerange, alternative = "greater", mu = 15) # is homerange more than 15
```

```{r 3, include=TRUE}
t.test(titi_ppt, alternative = "less", mu = 15) # is ppt greater than 15
```

```{r 4, include=TRUE}
t.test(titi_homerange, titi_ppt)
```

```{r 5, include=TRUE}
# oi jags innit
n_iter <- 20000 # we're going to generate 20000 samples
n_burnin <- 5000 # we're going to throw 5000 samples away as the model gets comfy
n_adapt <- 5000 # we're  going throw another 5000 samples away 
# we're going to have a total of 10000 samples at the end of the data

n_homerange <- length(titi_homerange) 
n_ppt <- length(titi_ppt)
# these just happen to both be 7 but good practice to differentiate

# where do we want our model to start from?
# it doesn't really matter but why not start at the mean?
homerange_init <- mean(titi_homerange)
ppt_init <- mean(titi_ppt)

# note spoiler

# JAGS hates normal R data, you need to make a separate list for **JAGS**  <3
jags_data <- list(n_homerange = n_homerange, n_ppt = n_ppt, 
                  homerange = titi_homerange, ppt = titi_ppt)
jags_init <- list(lambda1 = homerange_init, 
                  lambda2 = ppt_init) # oi jags innit
```

```{r 6, include=TRUE}
x <- seq(0, 30, by = 0.01)
plot(x, dunif(x, min = 10, max = 20), type = "l", 
     main = "Uniform?",
     xlab = "Prior values",
     ylab = "Probabilities")
```

```{r 7, include=TRUE}
x <- seq(0, 30, by = 0.01)
plot(x, dnorm(x, mean = 15, sd = 3), type = "l", 
     main = "Normal?",
     xlab = "Prior values",
     ylab = "Probabilities")
```

```{r 8, include=TRUE}
x <- seq(0, 30, by = 0.01)
plot(x, dgamma(x, shape = 15, rate = 1), type = "l", 
     main = "Gamma?",
     xlab = "Prior values",
     ylab = "Probabilities")
```
```{r 9, include=TRUE}
set.seed(812) # feel free to change my seed <3
# we first need to make the model
jags_model <- "model{
  # likelihood
  for(i in 1:n_homerange){
  homerange[i] ~ dpois(lambda1)
  }
  for (i in 1:n_ppt){
  ppt[i] ~ dpois(lambda2)
  }
  
  # prior
  lambda1 ~ dgamma(15, 1)
  lambda2 ~ dgamma(15, 1)
}"

fit <- jags.model(textConnection(jags_model),
               data = jags_data, inits = jags_init, 
               n.chains = 2, n.adapt = n_adapt) # what do the chains do?
```
```{r 10, include=TRUE}
# this saves the model as a variable

fit_samples <- coda.samples(fit, c("lambda1", "lambda2"), n.iter = n_iter) %>% 
  window(start = n_burnin + n_adapt) # let's get our samples <3
```
```{r 11, include=TRUE}
plot(window(fit_samples), density = FALSE) # this is a trace plot (tells us where we're randomly walking)
```

```{r 12, include=TRUE}
plot(window(fit_samples), trace = FALSE) # this is a density plot (you know what this is!)
```

```{r 13, include=TRUE}
summary(window(fit_samples)) # these are our samples
```

```{r 14, include=TRUE}
fit_samples <- as.data.frame(as.array(fit_samples)) # got to make a df

acf(fit_samples$lambda1.1)
```

```{r 15, include=TRUE}
acf(fit_samples$lambda1.2)
```

```{r 16, include=TRUE}
# let's do another diagnostic, when we're walking around, we need to guarantee that samples, from say 10 samples ago, aren't influencing the current sample. ACF plot! 
acf(fit_samples$lambda2.1)
```

```{r 17, include=TRUE}
acf(fit_samples$lambda2.2)
```

```{r 18, include=TRUE}
# all of these look great! autocorrelation between sample 1 and sample 3 is basically 0, good model (you want your model to be between the blue dotted lines I'd say before lag 10)

# we've got two chains, so we need to concatenate our dudes
fit_samples <- data.frame(homerange = 
                            c(fit_samples[, "lambda1.1"], 
                              fit_samples[, "lambda1.2"]),
                          ppt = 
                            c(fit_samples[, "lambda2.1"],
                                  fit_samples[, "lambda2.2"]))
```

```{r 19, include=TRUE}
colors <- c("Homerange" = "orange3", "Playback point transect" = "steelblue3")
# let's put our two samples against each other
fit_samples %>% ggplot() + # ggplot them
  geom_density(aes(x = homerange, fill = "Homerange", alpha = 0.5)) +
  geom_density(aes(x = ppt, fill = "Playback point transect", alpha = 0.5)) +
  xlab("Lambda Samples") +
  ggtitle("Posterior distributions of Homerange\nand Playback point transect lambdas") +
  scale_fill_manual(values = colors) +
  geom_vline(xintercept = 15, linetype = 3) + 
  guides(alpha="none")
```

```{r 20, include=TRUE}
# what percentage are less than 15?
ppt_credinterval <- quantile(fit_samples$ppt, probs = c(0.025, 0.975)); ppt_credinterval
```

```{r 21, include=TRUE}
# the probability lambda < 15
ppt_problessthan <- sum(fit_samples$ppt < 15)/length(fit_samples$ppt); ppt_problessthan
```

```{r 22, include=TRUE}
# credible interval
hr_credinterval <- quantile(fit_samples$homerange, probs = c(0.025, 0.975)); hr_credinterval
```

```{r 23, include=TRUE}
# the probability lambda > 15
hr_probmorethan <- sum(fit_samples$homerange > 15)/length(fit_samples$homerange); hr_probmorethan
```

```{r 24, include=TRUE}
diff_data <- fit_samples$homerange - fit_samples$ppt # subtract the two samples, then create a credible interval!
diffr_credinterval <- quantile(diff_data, probs = c(0.025, 0.975)); diffr_credinterval
```

```{r 25, include=TRUE}
# okay but what's the probability homerange estimates more than ppt?
diffr_prop <- sum(diff_data > 0)/length(diff_data); diffr_prop
```

```{r 26, include=TRUE}
jags_data <- list(n_homerange = n_homerange, n_ppt = n_ppt, 
                  homerange = titi_homerange, ppt = titi_ppt)
jags_init <- list(lambda1 = homerange_init, 
                  lambda2 = ppt_init)
```

```{r 27, include=TRUE}
set.seed(812) # feel free to change my seed <3
# we first need to make the model
jags_model <- "model{
  # likelihood
  for(i in 1:n_homerange){
  homerange[i] ~ dpois(lambda1)
  }
  for (i in 1:n_ppt){
  ppt[i] ~ dpois(lambda2)
  }
  
  # prior
  lambda1 ~ dnorm(15, 1/9)
  lambda2 ~ dnorm(15, 1/9)
}"

fit_norm <- jags.model(textConnection(jags_model),
               data = jags_data, inits = jags_init, 
               n.chains = 2, n.adapt = n_adapt) # what do the chains do?
```

```{r 28, include=TRUE}
# this saves the model as a variable

fit_samples_norm <- coda.samples(fit_norm, c("lambda1", "lambda2"), n.iter = n_iter) %>% 
  window(start = n_burnin + n_adapt) # let's get our samples <3
```

```{r 29, include=TRUE}
plot(window(fit_samples_norm), density = FALSE) # this is a trace plot (tells us where we're randomly walking)
```

```{r 30, include=TRUE}
plot(window(fit_samples_norm), trace = FALSE) # this is a density plot (you know what this is!)
```

```{r 31, include=TRUE}
summary(window(fit_samples_norm)) # these are our samples
```

```{r 32, include=TRUE}
fit_samples_norm <- as.data.frame(as.array(fit_samples_norm)) # got to make a df

acf(fit_samples_norm$lambda1.1) # notice how we have a bit more lag, sample i is influencing i+1 a bit more than w the poisson-gamma
```

```{r 33, include=TRUE}
acf(fit_samples_norm$lambda1.2)
```

```{r 34, include=TRUE}
# let's do another diagnostic, when we're walking around, we need to guarantee that samples, from say 10 samples ago, aren't influencing the current sample. ACF plot! 
acf(fit_samples_norm$lambda2.1)
```

```{r 35, include=TRUE}
acf(fit_samples_norm$lambda2.2)
```

```{r 36, include=TRUE}
# all of these look great! autocorrelation between sample 1 and sample 3 is basically 0, good model (you want your model to be between the blue dotted lines I'd say before lag 10)

# we've got two chains, so we need to concatenate our dudes
fit_samples_norm <- data.frame(homerange = 
                            c(fit_samples_norm[, "lambda1.1"], 
                              fit_samples_norm[, "lambda1.2"]),
                          ppt = 
                            c(fit_samples_norm[, "lambda2.1"],
                                  fit_samples_norm[, "lambda2.2"]))
```

```{r 36, include=TRUE}
colors <- c("Gamma" = "orange3", "Normal" = "steelblue3")
# let's put our two samples against each other
ggplot() + # ggplot them
  geom_density(aes(x = fit_samples$homerange, fill = "Gamma", alpha = 0.5)) +
  geom_density(aes(x = fit_samples_norm$homerange, fill = "Normal", alpha = 0.5)) +
  xlab("Lambda Samples") +
  ggtitle("Posterior distributions of Homerange\nfor Gamma and Normal Priors") +
  scale_fill_manual(values = colors) +
  geom_vline(xintercept = 15, linetype = 3) + 
  guides(alpha="none")
```

```{r 37, include=TRUE}
ggplot() + # ggplot them
  geom_density(aes(x = fit_samples$ppt, fill = "Gamma", alpha = 0.5)) +
  geom_density(aes(x = fit_samples_norm$ppt, fill = "Normal", alpha = 0.5)) +
  xlab("Lambda Samples") +
  ggtitle("Posterior distributions of Playback point transect\nfor Gamma and Normal Priors") +
  scale_fill_manual(values = colors) +
  geom_vline(xintercept = 15, linetype = 3) + 
  guides(alpha="none")
```

```{r 38, include=TRUE}
# credible interval
hr_normcredinterval <- quantile(fit_samples_norm$homerange, probs = c(0.025, 0.975)); hr_normcredinterval
```

```{r 39, include=TRUE}
# the probability lambda > 15
hr_normprobmorethan <- sum(fit_samples_norm$homerange > 15)/length(fit_samples_norm$homerange);
hr_normprobmorethan
```

```{r 40, include=TRUE}
ppt_normcredinterval <- quantile(fit_samples_norm$ppt, probs = c(0.025, 0.975)); ppt_normcredinterval
```

```{r 41, include=TRUE}
# the probability lambda < 15
ppt_normprobmorethan <- sum(fit_samples_norm$ppt < 15)/length(fit_samples_norm$ppt);
ppt_normprobmorethan
```

```{r 42, include=TRUE}
diff_data <- fit_samples_norm$homerange - fit_samples_norm$ppt # subtract the two samples, then create a credible interval!
diffr_credinterval <- quantile(diff_data, probs = c(0.025, 0.975)); diffr_credinterval
```

```{r 43, include=TRUE}
# okay but what's the probability homerange estimates more than ppt?
diffr_prop <- sum(diff_data > 0)/length(diff_data); diffr_prop
```


